# Generated by Django 3.0.7 on 2020-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='safeplacesdistance',
            field=models.CharField(default='km', max_length=200),
        ),
    ]
